export enum GitStatus {
    CLEAN,
    DELETED,
    MODIFIED,
    STAGED,
    STAGED_ADDED,
    STAGED_COPIED,
    STAGED_DELETED,
    STAGED_MODIFIED,
    STAGED_RENAMED,
    STAGED_TYPE,
    STAGED_UNKNOWN,
    STAGED_UNMERGED,
    UNTRACKED
}
