
export enum OCTICONS {
    ALERT,
    ARROW_DOWN,
    ARROW_LEFT,
    ARROW_RIGHT,
    ARROW_SMALL_DOWN,
    ARROW_SMALL_LEFT,
    ARROW_SMALL_RIGHT,
    ARROW_SMALL_UP,
    ARROW_UP,
    BEAKER,
    BELL,
    BOLD,
    BOOK,
    BOOKMARK,
    BRIEFCASE,
    BROADCAST,
    BROWSER,
    BUG,
    CALENDAR,
    CHECK,
    CHECKLIST,
    CHEVRON_DOWN,
    CHEVRON_LEFT,
    CHEVRON_RIGHT,
    CHEVRON_UP,
    CIRCLE_SLASH,
    CIRCUIT_BOARD,
    CLIPPY,
    CLOCK,
    CLOUD_DOWNLOAD,
    CLOUD_UPLOAD,
    CODE,
    COMMENT,
    COMMENT_DISCUSSION,
    CREDIT_CARD,
    DASH,
    DASHBOARD,
    DATABASE,
    DESKTOP_DOWNLOAD,
    DEVICE_CAMERA,
    DEVICE_CAMERA_VIDEO,
    DEVICE_DESKTOP,
    DEVICE_MOBILE,
    DIFF,
    DIFF_ADDED,
    DIFF_IGNORED,
    DIFF_MODIFIED,
    DIFF_REMOVED,
    DIFF_RENAMED,
    ELLIPSIS,
    EYE,
    FILE_BINARY,
    FILE_CODE,
    FILE_DIRECTORY,
    FILE_MEDIA,
    FILE_PDF,
    FILE_SUBMODULE,
    FILE_SYMLINK_DIRECTORY,
    FILE_SYMLINK_FILE,
    FILE_TEXT,
    FILE_ZIP,
    FLAME,
    FOLD,
    GEAR,
    GIFT,
    GIST,
    GIST_SECRET,
    GIT_BRANCH,
    GIT_COMMIT,
    GIT_COMPARE,
    GIT_MERGE,
    GIT_PULL_REQUEST,
    GLOBE,
    GRAPH,
    HEART,
    HISTORY,
    HOME,
    HORIZONTAL_RULE,
    HUBOT,
    INBOX,
    INFO,
    ISSUE_CLOSED,
    ISSUE_OPENED,
    ISSUE_REOPENED,
    ITALIC,
    JERSEY,
    KEY,
    KEYBOARD,
    LAW,
    LIGHT_BULB,
    LINK,
    LINK_EXTERNAL,
    LIST_ORDERED,
    LIST_UNORDERED,
    LOCATION,
    LOCK,
    LOGO_GIST,
    LOGO_GITHUB,
    MAIL,
    MAIL_READ,
    MAIL_REPLY,
    MARKDOWN,
    MARK_GITHUB,
    MEGAPHONE,
    MENTION,
    MILESTONE,
    MIRROR,
    MORTAR_BOARD,
    MUTE,
    NO_NEWLINE,
    OCTOFACE,
    ORGANIZATION,
    PACKAGE,
    PAINTCAN,
    PENCIL,
    PERSON,
    PIN,
    PLUG,
    PLUS,
    PRIMITIVE_DOT,
    PRIMITIVE_SQUARE,
    PULSE,
    QUESTION,
    QUOTE,
    RADIO_TOWER,
    REPO,
    REPO_CLONE,
    REPO_FORCE_PUSH,
    REPO_FORKED,
    REPO_PULL,
    REPO_PUSH,
    ROCKET,
    RSS,
    RUBY,
    SEARCH,
    SERVER,
    SETTINGS,
    SHIELD,
    SIGN_IN,
    SIGN_OUT,
    SMILEY,
    SQUIRREL,
    STAR,
    STOP,
    SYNC,
    TAG,
    TASKLIST,
    TELESCOPE,
    TERMINAL,
    TEXT_SIZE,
    THREE_BARS,
    THUMBSDOWN,
    THUMBSUP,
    TOOLS,
    TRASHCAN,
    TRIANGLE_DOWN,
    TRIANGLE_LEFT,
    TRIANGLE_RIGHT,
    TRIANGLE_UP,
    UNFOLD,
    UNMUTE,
    UNVERIFIED,
    VERIFIED,
    VERSIONS,
    WATCH,
    X,
    ZAP
}

export function getOcticon(octicon: OCTICONS): string {
    return OCTICONS_SET.get(octicon);
}

const OCTICONS_SET = new Map<OCTICONS, string>();
OCTICONS_SET.set(OCTICONS.ALERT, "alert");
OCTICONS_SET.set(OCTICONS.ARROW_DOWN, "arrow-down");
OCTICONS_SET.set(OCTICONS.ARROW_LEFT, "arrow-left");
OCTICONS_SET.set(OCTICONS.ARROW_RIGHT, "arrow-right");
OCTICONS_SET.set(OCTICONS.ARROW_SMALL_DOWN, "arrow-small-down");
OCTICONS_SET.set(OCTICONS.ARROW_SMALL_LEFT, "arrow-small-left");
OCTICONS_SET.set(OCTICONS.ARROW_SMALL_RIGHT, "arrow-small-right");
OCTICONS_SET.set(OCTICONS.ARROW_SMALL_UP, "arrow-small-up");
OCTICONS_SET.set(OCTICONS.ARROW_UP, "arrow-up");
OCTICONS_SET.set(OCTICONS.BEAKER, "beaker");
OCTICONS_SET.set(OCTICONS.BELL, "bell");
OCTICONS_SET.set(OCTICONS.BOLD, "bold");
OCTICONS_SET.set(OCTICONS.BOOK, "book");
OCTICONS_SET.set(OCTICONS.BOOKMARK, "bookmark");
OCTICONS_SET.set(OCTICONS.BRIEFCASE, "briefcase");
OCTICONS_SET.set(OCTICONS.BROADCAST, "broadcast");
OCTICONS_SET.set(OCTICONS.BROWSER, "browser");
OCTICONS_SET.set(OCTICONS.BUG, "bug");
OCTICONS_SET.set(OCTICONS.CALENDAR, "calendar");
OCTICONS_SET.set(OCTICONS.CHECK, "check");
OCTICONS_SET.set(OCTICONS.CHECKLIST, "checklist");
OCTICONS_SET.set(OCTICONS.CHEVRON_DOWN, "chevron-down");
OCTICONS_SET.set(OCTICONS.CHEVRON_LEFT, "chevron-left");
OCTICONS_SET.set(OCTICONS.CHEVRON_RIGHT, "chevron-right");
OCTICONS_SET.set(OCTICONS.CHEVRON_UP, "chevron-up");
OCTICONS_SET.set(OCTICONS.CIRCLE_SLASH, "circle-slash");
OCTICONS_SET.set(OCTICONS.CIRCUIT_BOARD, "circuit-board");
OCTICONS_SET.set(OCTICONS.CLIPPY, "clippy");
OCTICONS_SET.set(OCTICONS.CLOCK, "clock");
OCTICONS_SET.set(OCTICONS.CLOUD_DOWNLOAD, "cloud-download");
OCTICONS_SET.set(OCTICONS.CLOUD_UPLOAD, "cloud-upload");
OCTICONS_SET.set(OCTICONS.CODE, "code");
OCTICONS_SET.set(OCTICONS.COMMENT, "comment");
OCTICONS_SET.set(OCTICONS.COMMENT_DISCUSSION, "comment-discussion");
OCTICONS_SET.set(OCTICONS.CREDIT_CARD, "credit-card");
OCTICONS_SET.set(OCTICONS.DASH, "dash");
OCTICONS_SET.set(OCTICONS.DASHBOARD, "dashboard");
OCTICONS_SET.set(OCTICONS.DATABASE, "database");
OCTICONS_SET.set(OCTICONS.DESKTOP_DOWNLOAD, "desktop-download");
OCTICONS_SET.set(OCTICONS.DEVICE_CAMERA, "device-camera");
OCTICONS_SET.set(OCTICONS.DEVICE_CAMERA_VIDEO, "device-camera-video");
OCTICONS_SET.set(OCTICONS.DEVICE_DESKTOP, "device-desktop");
OCTICONS_SET.set(OCTICONS.DEVICE_MOBILE, "device-mobile");
OCTICONS_SET.set(OCTICONS.DIFF, "diff");
OCTICONS_SET.set(OCTICONS.DIFF_ADDED, "diff-added");
OCTICONS_SET.set(OCTICONS.DIFF_IGNORED, "diff-ignored");
OCTICONS_SET.set(OCTICONS.DIFF_MODIFIED, "diff-modified");
OCTICONS_SET.set(OCTICONS.DIFF_REMOVED, "diff-removed");
OCTICONS_SET.set(OCTICONS.DIFF_RENAMED, "diff-renamed");
OCTICONS_SET.set(OCTICONS.ELLIPSIS, "ellipsis");
OCTICONS_SET.set(OCTICONS.EYE, "eye");
OCTICONS_SET.set(OCTICONS.FILE_BINARY, "file-binary");
OCTICONS_SET.set(OCTICONS.FILE_CODE, "file-code");
OCTICONS_SET.set(OCTICONS.FILE_DIRECTORY, "file-directory");
OCTICONS_SET.set(OCTICONS.FILE_MEDIA, "file-media");
OCTICONS_SET.set(OCTICONS.FILE_PDF, "file-pdf");
OCTICONS_SET.set(OCTICONS.FILE_SUBMODULE, "file-submodule");
OCTICONS_SET.set(OCTICONS.FILE_SYMLINK_DIRECTORY, "file-symlink-directory");
OCTICONS_SET.set(OCTICONS.FILE_SYMLINK_FILE, "file-symlink-file");
OCTICONS_SET.set(OCTICONS.FILE_TEXT, "file-text");
OCTICONS_SET.set(OCTICONS.FILE_ZIP, "file-zip");
OCTICONS_SET.set(OCTICONS.FLAME, "flame");
OCTICONS_SET.set(OCTICONS.FOLD, "fold");
OCTICONS_SET.set(OCTICONS.GEAR, "gear");
OCTICONS_SET.set(OCTICONS.GIFT, "gift");
OCTICONS_SET.set(OCTICONS.GIST, "gist");
OCTICONS_SET.set(OCTICONS.GIST_SECRET, "gist-secret");
OCTICONS_SET.set(OCTICONS.GIT_BRANCH, "git-branch");
OCTICONS_SET.set(OCTICONS.GIT_COMMIT, "git-commit");
OCTICONS_SET.set(OCTICONS.GIT_COMPARE, "git-compare");
OCTICONS_SET.set(OCTICONS.GIT_MERGE, "git-merge");
OCTICONS_SET.set(OCTICONS.GIT_PULL_REQUEST, "git-pull-request");
OCTICONS_SET.set(OCTICONS.GLOBE, "globe");
OCTICONS_SET.set(OCTICONS.GRAPH, "graph");
OCTICONS_SET.set(OCTICONS.HEART, "heart");
OCTICONS_SET.set(OCTICONS.HISTORY, "history");
OCTICONS_SET.set(OCTICONS.HOME, "home");
OCTICONS_SET.set(OCTICONS.HORIZONTAL_RULE, "horizontal-rule");
OCTICONS_SET.set(OCTICONS.HUBOT, "hubot");
OCTICONS_SET.set(OCTICONS.INBOX, "inbox");
OCTICONS_SET.set(OCTICONS.INFO, "info");
OCTICONS_SET.set(OCTICONS.ISSUE_CLOSED, "issue-closed");
OCTICONS_SET.set(OCTICONS.ISSUE_OPENED, "issue-opened");
OCTICONS_SET.set(OCTICONS.ISSUE_REOPENED, "issue-reopened");
OCTICONS_SET.set(OCTICONS.ITALIC, "italic");
OCTICONS_SET.set(OCTICONS.JERSEY, "jersey");
OCTICONS_SET.set(OCTICONS.KEY, "key");
OCTICONS_SET.set(OCTICONS.KEYBOARD, "keyboard");
OCTICONS_SET.set(OCTICONS.LAW, "law");
OCTICONS_SET.set(OCTICONS.LIGHT_BULB, "light-bulb");
OCTICONS_SET.set(OCTICONS.LINK, "link");
OCTICONS_SET.set(OCTICONS.LINK_EXTERNAL, "link-external");
OCTICONS_SET.set(OCTICONS.LIST_ORDERED, "list-ordered");
OCTICONS_SET.set(OCTICONS.LIST_UNORDERED, "list-unordered");
OCTICONS_SET.set(OCTICONS.LOCATION, "location");
OCTICONS_SET.set(OCTICONS.LOCK, "lock");
OCTICONS_SET.set(OCTICONS.LOGO_GIST, "logo-gist");
OCTICONS_SET.set(OCTICONS.LOGO_GITHUB, "logo-github");
OCTICONS_SET.set(OCTICONS.MAIL, "mail");
OCTICONS_SET.set(OCTICONS.MAIL_READ, "mail-read");
OCTICONS_SET.set(OCTICONS.MAIL_REPLY, "mail-reply");
OCTICONS_SET.set(OCTICONS.MARK_GITHUB, "mark-github");
OCTICONS_SET.set(OCTICONS.MARKDOWN, "markdown");
OCTICONS_SET.set(OCTICONS.MEGAPHONE, "megaphone");
OCTICONS_SET.set(OCTICONS.MENTION, "mention");
OCTICONS_SET.set(OCTICONS.MILESTONE, "milestone");
OCTICONS_SET.set(OCTICONS.MIRROR, "mirror");
OCTICONS_SET.set(OCTICONS.MORTAR_BOARD, "mortar-board");
OCTICONS_SET.set(OCTICONS.MUTE, "mute");
OCTICONS_SET.set(OCTICONS.NO_NEWLINE, "no-newline");
OCTICONS_SET.set(OCTICONS.OCTOFACE, "octoface");
OCTICONS_SET.set(OCTICONS.ORGANIZATION, "organization");
OCTICONS_SET.set(OCTICONS.PACKAGE, "package");
OCTICONS_SET.set(OCTICONS.PAINTCAN, "paintcan");
OCTICONS_SET.set(OCTICONS.PENCIL, "pencil");
OCTICONS_SET.set(OCTICONS.PERSON, "person");
OCTICONS_SET.set(OCTICONS.PIN, "pin");
OCTICONS_SET.set(OCTICONS.PLUG, "plug");
OCTICONS_SET.set(OCTICONS.PLUS, "plus");
OCTICONS_SET.set(OCTICONS.PRIMITIVE_DOT, "primitive-dot");
OCTICONS_SET.set(OCTICONS.PRIMITIVE_SQUARE, "primitive-square");
OCTICONS_SET.set(OCTICONS.PULSE, "pulse");
OCTICONS_SET.set(OCTICONS.QUESTION, "question");
OCTICONS_SET.set(OCTICONS.QUOTE, "quote");
OCTICONS_SET.set(OCTICONS.RADIO_TOWER, "radio-tower");
OCTICONS_SET.set(OCTICONS.REPO, "repo");
OCTICONS_SET.set(OCTICONS.REPO_CLONE, "repo-clone");
OCTICONS_SET.set(OCTICONS.REPO_FORCE_PUSH, "repo-force-push");
OCTICONS_SET.set(OCTICONS.REPO_FORKED, "repo-forked");
OCTICONS_SET.set(OCTICONS.REPO_PULL, "repo-pull");
OCTICONS_SET.set(OCTICONS.REPO_PUSH, "repo-push");
OCTICONS_SET.set(OCTICONS.ROCKET, "rocket");
OCTICONS_SET.set(OCTICONS.RSS, "rss");
OCTICONS_SET.set(OCTICONS.RUBY, "ruby");
OCTICONS_SET.set(OCTICONS.SEARCH, "search");
OCTICONS_SET.set(OCTICONS.SERVER, "server");
OCTICONS_SET.set(OCTICONS.SETTINGS, "settings");
OCTICONS_SET.set(OCTICONS.SHIELD, "shield");
OCTICONS_SET.set(OCTICONS.SIGN_IN, "sign-in");
OCTICONS_SET.set(OCTICONS.SIGN_OUT, "sign-out");
OCTICONS_SET.set(OCTICONS.SMILEY, "smiley");
OCTICONS_SET.set(OCTICONS.SQUIRREL, "squirrel");
OCTICONS_SET.set(OCTICONS.STAR, "star");
OCTICONS_SET.set(OCTICONS.STOP, "stop");
OCTICONS_SET.set(OCTICONS.SYNC, "sync");
OCTICONS_SET.set(OCTICONS.TAG, "tag");
OCTICONS_SET.set(OCTICONS.TASKLIST, "tasklist");
OCTICONS_SET.set(OCTICONS.TELESCOPE, "telescope");
OCTICONS_SET.set(OCTICONS.TERMINAL, "terminal");
OCTICONS_SET.set(OCTICONS.TEXT_SIZE, "text-size");
OCTICONS_SET.set(OCTICONS.THREE_BARS, "three-bars");
OCTICONS_SET.set(OCTICONS.THUMBSDOWN, "thumbsdown");
OCTICONS_SET.set(OCTICONS.THUMBSUP, "thumbsup");
OCTICONS_SET.set(OCTICONS.TOOLS, "tools");
OCTICONS_SET.set(OCTICONS.TRASHCAN, "trashcan");
OCTICONS_SET.set(OCTICONS.TRIANGLE_DOWN, "triangle-down");
OCTICONS_SET.set(OCTICONS.TRIANGLE_LEFT, "triangle-left");
OCTICONS_SET.set(OCTICONS.TRIANGLE_RIGHT, "triangle-right");
OCTICONS_SET.set(OCTICONS.TRIANGLE_UP, "triangle-up");
OCTICONS_SET.set(OCTICONS.UNFOLD, "unfold");
OCTICONS_SET.set(OCTICONS.UNMUTE, "unmute");
OCTICONS_SET.set(OCTICONS.UNVERIFIED, "unverified");
OCTICONS_SET.set(OCTICONS.VERIFIED, "verified");
OCTICONS_SET.set(OCTICONS.VERSIONS, "versions");
OCTICONS_SET.set(OCTICONS.WATCH, "watch");
OCTICONS_SET.set(OCTICONS.X, "x");
OCTICONS_SET.set(OCTICONS.ZAP, "zap");
